### PR TITLE
Basic example

### LINKED ISSUE #14: MWE?
Hi,

This looks super useful! I'd love to implement it in some of my work. Do you all have a minimal working example to get started? Maybe something as simple as counting the number of reads on each chromosome with `pararead` compared to a typical `pysam` implementation?

### PR DESCRIPTION
**Pull request by vreuter**
To make the package more approachable, these changes provide a basic example for an implementation of a `ParaReadProcessor`. Close #14

### CODE REVIEW

**Comment by nsheff** [comment]
This worked for me on 1 core, but on 2 cores I'm getting an error... I tried to extend the script to take the core count on the command line (otherwise it's kind of useless to use pararead), but it's failing with some aligned data from microtest:

With 1 core:
```
nsheff@puma:~/code/pararead/examples$ python count_reads.py ~/code/microtest/data/bs_aln_k1k3.bam -O test.txt -C 1
Configured logger 'root' using pararead v0.5.0-dev
Output file already exists and will be overwritten: 'test.txt'
Registering input file: '/home/nsheff/code/microtest/data/bs_aln_k1k3.bam'
Counting reads: /home/nsheff/code/microtest/data/bs_aln_k1k3.bam
Temporary files will be stored in: 'tmp_bs_aln_k1k3_CountReads_qpdtBT'
Processing with 1 cores...
Discarding 0 chunk(s) of reads: []
Keeping 2 chunk(s) of reads: ['K1_unmethylated', 'K3_methylated']
Collecting read counts: test.txt
Merging 2 files into output file: 'test.txt'
```

With 2 cores:
```
nsheff@puma:~/code/pararead/examples$ python count_reads.py ~/code/microtest/data/bs_aln_k1k3.bam -O test.txt -C 2
Configured logger 'root' using pararead v0.5.0-dev
Output file already exists and will be overwritten: 'test.txt'
Registering input file: '/home/nsheff/code/microtest/data/bs_aln_k1k3.bam'
Counting reads: /home/nsheff/code/microtest/data/bs_aln_k1k3.bam
Temporary files will be stored in: 'tmp_bs_aln_k1k3_CountReads_xIE8wT'
Processing with 2 cores...
[E::bgzf_read] Read block operation failed with error -1 after 0 of 4 bytes
Traceback (most recent call last):
  File "count_reads.py", line 51, in <module>
    main(sys.argv[1:])
  File "count_reads.py", line 45, in main
    good_chromosomes = counter.run()
  File "/home/nsheff/.local/lib/python2.7/site-packages/pararead/processor.py", line 479, in run
    results = workers.map_async(self, nonempties).get(9999999)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
IOError: truncated file
```

**Comment by vreuter** [comment]
Yeah, I'd wanted to maximize the basic-ness, but you're right--`cores` makes sense. I can't reproduce the error; your changes work for me, using both `--cores` and `-C`. The error has data file dependence. Your changes work fine on the test BAM I was using, but it does in fact recur on that spike-in file.

**Comment by vreuter** [comment]
Ah, maybe the spike-in file is unaligned...is that the case? `count_reads` is using an `AlignmentFile` instance.

**Comment by nsheff** [comment]
No, it's aligned; it only makes sense to use pararead on aligned files at the moment (can't index into unaligned files)

**Comment by nsheff** [comment]
>  The error has data file dependence. Your changes work fine on the test BAM I was using, but it does in fact recur on that spike-in file.

Well, this seems like a separate issue then. I think the MWE is working fine.

But this brings up apparently a different bug with pararead, maybe having to do with the tiny file.

**Comment by nsheff** [comment]
I will start a new issue with that bug.

**Comment by caleblareau** [comment]
Looks good to me; I was able to reproduce the example. Thanks!!

**Pull request merged**
